name: build

on: 
  workflow_dispatch:
  push:
    branches: [ main, dev, 'dev/*', 'feature/*', 'rel/*' ]
    paths-ignore:
      - readme.md
  pull_request:
    types: [opened, synchronize, reopened]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          submodules: recursive
          fetch-depth: 0
          
      - run: mkdir build
      - run: cmake .. -DCMAKE_BUILD_TYPE=Debug
        working-directory: ./build
      - run: cmake --build .
        working-directory: ./build
#      - run: ctest . -C Debug --label-exclude slow --no-label-summary
#        working-directory: ./build



        